### PR TITLE
Expand tests, including exception handling, and tweaks

### PR DESCRIPTION
**Pull request by anthonylangsworth**
I expanded the testing, particularly of throwing exceptions on invalid arguments. To do this, I switched the default test framework from MSTest to NUnit. While this requires an additional download to run the tests (the [Visual Studio NUnit 3 Test Adapter](https://visualstudiogallery.msdn.microsoft.com/0da0f6bd-9bb6-4ae3-87a8-537788622f2d) or Resharper), there are already a few libraries downloaded by this project, anyway, 

Lots of minor tweaks, including:
1. Use new C# features, e.g. nameof. This may be controversial because it requires later versions of Visual Studio but the project already requires .Net 4.5.
2. Add missing XML comments.
3. Typo in README.md.
4. Adding root level files (e.g. README.md, LICENSE and VERSION) as solution items.

### CODE REVIEW

**Comment by anthonylangsworth** [comment]
I will take a look at the failing tests. I am not sure whether NUnit works under Mono.

**Comment by anthonylangsworth** [comment]
Thanks, @simeon-aladjem . I just have to get the latest version of NUnit working under mono. I'll keep working through this over the next few days.

**Comment by simeon-aladjem** [comment]
I see now that tests fail with this message
```
The command "xbuild /p:Configuration=Release Authentication.sln" exited with 0.
$ mono ./target/NUnit.Runners.3.4.1/tools/nunit-console.exe ./MiraclAuthenticationTests/bin/Release/MiraclAuthenticationTests.dll
Cannot open assembly './target/NUnit.Runners.3.4.1/tools/nunit-console.exe': No such file or directory.
The command "mono ./target/NUnit.Runners.3.4.1/tools/nunit-console.exe ./MiraclAuthenticationTests/bin/Release/MiraclAuthenticationTests.dll" exited with 2.
```

**Comment by anthonylangsworth** [comment]
Thanks again, @simeon-aladjem . Fixed. I may expand the tests over a few days but feedback is welcome.

**Comment by nicolaasuni** [comment]
LGTM

**Comment by simeon-aladjem** [comment]
LGTM

**Comment by tatiNo5** [comment]
LGTM too!

**Pull request merged**
